CREATE TABLE app_user (username VARCHAR(40) PRIMARY KEY, tenant_id VARCHAR(40) NOT NULL);
CREATE TABLE invoice (id VARCHAR(40) PRIMARY KEY, tenant_id VARCHAR(40) NOT NULL, customer VARCHAR(80) NOT NULL, amount_cents BIGINT NOT NULL);
CREATE TABLE export_job (id BIGINT AUTO_INCREMENT PRIMARY KEY, requester VARCHAR(40) NOT NULL, invoice_id VARCHAR(40) NOT NULL, status VARCHAR(20) NOT NULL, content VARCHAR(400));
